cmake_minimum_required(VERSION 4.2)
project(untitled1)

set(CMAKE_CXX_STANDARD 20)

add_executable(untitled1 HOAFUCKTION2/HOA_1_1_FUNCTION_2.cpp
        HOA_1_1_FUNCTION_1.cpp
        HOA_1_1_FUNCTION_3.cpp
        "HOA ILO B.cpp"
        ILOC-1.cpp
        ILOC2.cpp
        ILOC-3.cpp
        ILOC-4.cpp
        "TRIAL .cpp"
        "ILO C  ACT 2.1.cpp"
        "July 21 2026 - DSA.cpp"
        "July 21 2026 - DSA.cpp"
        "July 21 2026 - DSA.cpp"
        "July 21 2026 - DSA.cpp"
        "main.cpp"
        "main.h"
        Mendoza_Roy_Doubly_LL_July23.cpp
        Mendoza_Roy_Doubly_LL_July23.h
        Mendoza_Roy_Doubly_LL_July23.h
        HOA3_SUP_Mendoza.cpp
        Playlist.h
        "TRAIL IMPLE.cpp"
        "main to doubly.cpp"
        "main to doubly.h"
        STACKS.h
        keyufg.cpp
        "Mendoza_Roy_Seatwork4_1_b1.cpp..cpp"
        Mendoza_Roy_Seatwork4_1.cpp..cpp
        "Stack Using Linked Lists.cpp"
        "HOA4 SUP ACT.cpp"
        HOA4sup.h
        "HOA 5p1/ILOA.cpp"
        "HOA 5p1/ILOB.cpp"
        "HOA 5p1/queuell.h"
        "HOA 5p1/queueArr.h"
        "HOA 5p1/ILOB.2.cpp"
        "HOA 5p1/newQArr.h"
        "HOA 5p1/newQArr.cpp"
        "HOA 5p1/sup5.1.h"
        "HOA 5p1/sup5.1.cpp"
        "HOA 5p1/Job.h"
        "HOA 5p1/printer.h"
        "HOA6p1/Aug 18 2026.cpp"
        HOA6p1/nodes.h
        HOA6p1/searchingAlgo.h
        "HOA6p1/ILO A.cpp"
        "HOA6p1/SUPPLEMENTARY/Sup main.cpp"
        HOA6p1/SUPPLEMENTARY/nodes.h
        HOA6p1/SUPPLEMENTARY/searchingalgo.h
        HOA6p1/SUPPLEMENTARY/SUP2.cpp
        HOA6p1/SUPPLEMENTARY/Sup3.cpp
        HOA6p1/SUPPLEMENTARY/sup4.cpp
        "Preparatory files/palindrome.h"
        "Preparatory files/palindrome.cpp"
        "Preparatory files/arraycheckere.h"
        "Preparatory files/checkermain.cpp")
